package redrum;

import dao.DataSource;
import dao.daoUsers;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *
 * @author Aluno TDS
 */
public class JFCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastro
     */
    public JFCadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        CriarJanelaCadastro = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTFEmail = new javax.swing.JTextField();
        jTFNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        CriarJanelaCadastro1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Redrum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(158, 0, 0))); // NOI18N

        jTFNome.setForeground(new java.awt.Color(153, 153, 153));
        jTFNome.setText("Nome");
        jTFNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNomeFocusLost(evt);
            }
        });
        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jTFTelefone.setForeground(new java.awt.Color(153, 153, 153));
        jTFTelefone.setText("Telefone");
        jTFTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTelefoneFocusLost(evt);
            }
        });
        jTFTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefoneActionPerformed(evt);
            }
        });

        jTFEndereco.setForeground(new java.awt.Color(153, 153, 153));
        jTFEndereco.setText("Endereço");
        jTFEndereco.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTFEnderecoAncestorRemoved(evt);
            }
        });
        jTFEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEnderecoFocusLost(evt);
            }
        });
        jTFEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEnderecoActionPerformed(evt);
            }
        });

        CriarJanelaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CriarJanelaCadastro.setForeground(new java.awt.Color(158, 0, 0));
        CriarJanelaCadastro.setText("Cadastre-se");
        CriarJanelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarJanelaCadastroActionPerformed(evt);
            }
        });

        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jTFEmail.setForeground(new java.awt.Color(153, 153, 153));
        jTFEmail.setText("E-mail");
        jTFEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEmailFocusLost(evt);
            }
        });
        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        jTFNumero.setForeground(new java.awt.Color(153, 153, 153));
        jTFNumero.setText("Número");
        jTFNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNumeroFocusLost(evt);
            }
        });
        jTFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(158, 0, 0));
        jLabel3.setText("Onde cada gota importa.");

        jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        CriarJanelaCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CriarJanelaCadastro1.setForeground(new java.awt.Color(158, 0, 0));
        CriarJanelaCadastro1.setText("Cancelar");
        CriarJanelaCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarJanelaCadastro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(CriarJanelaCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(CriarJanelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addComponent(jPasswordField1)
                    .addComponent(jTFEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordField2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarJanelaCadastro)
                    .addComponent(CriarJanelaCadastro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNomeFocusGained
        // TODO add your handling code here:
        if(jTFNome.getText().equals("Nome"))
        {
            jTFNome.setText("");
            jTFNome.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTFNomeFocusGained

    private void jTFNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNomeFocusLost
        // TODO add your handling code here:
        if(jTFNome.getText().equals(""))
        {
            jTFNome.setText("Nome");
            jTFNome.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTFNomeFocusLost

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
        CriarJanelaCadastroActionPerformed(evt);
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefoneFocusGained
        // TODO add your handling code here:
        if(jTFTelefone.getText().equals("Telefone"))
        {
            jTFTelefone.setText("");
            jTFTelefone.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTFTelefoneFocusGained

    private void jTFTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefoneFocusLost
        // TODO add your handling code here:
        if(jTFTelefone.getText().equals(""))
        {
            jTFTelefone.setText("Telefone");
            jTFTelefone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTFTelefoneFocusLost

    private void jTFEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEnderecoFocusGained
        // TODO add your handling code here:
        if(jTFEndereco.getText().equals("Endereço"))
        {
            jTFEndereco.setText("");
            jTFEndereco.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTFEnderecoFocusGained

    private void jTFEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEnderecoFocusLost
        // TODO add your handling code here:
        if(jTFEndereco.getText().equals(""))
        {
            jTFEndereco.setText("Endereço");
            jTFEndereco.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_jTFEnderecoFocusLost

    private void CriarJanelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarJanelaCadastroActionPerformed
        int flag = 0;

        // cria um datasource para conexão com o banco
        DataSource dataSource = new DataSource();

        // instancia um objeto
        daoUsers user = new daoUsers(dataSource);

        // cria um arraylist para jogar os dados recuperados dentro
        ArrayList<Usuarios> emails = user.validaUser(jTFEmail.getText());
       

        // verifica se a lista retornou vazia
        if(emails != null){

            // coloca as informações da lista na área de texto
            for(Usuarios u : emails){

                if ((u.getEmail().equals(jTFEmail.getText()))){
                    jPasswordField1.setText("");
                    jPasswordField2.setText("");
                    JOptionPane.showMessageDialog(null, "O e-mail já está em uso!");
                    flag = 15;
                }
                
                System.out.printf("%s - %s\n",u.getEmail(),u.getSenha());
          
            }
        }
        
        String pw = new String(jPasswordField1.getPassword());
        String pw2 = new String(jPasswordField2.getPassword());
        
        System.out.printf("\n%s\n\n",jTFNome.getText());
        System.out.printf("\n%s\n\n",jTFEndereco.getText());
        System.out.printf("\n%s\n\n",jTFTelefone.getText());
        System.out.printf("\n%s\n\n",jTFEmail.getText());
        System.out.printf("\n%s\n\n",pw);
        
        if (jTFNome.getText().equals("Nome") || jTFNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [Nome] não pode ser vazio!");
            flag = 2;
        }
        
        if (jTFTelefone.getText().equals("Telefone") || jTFTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [Telefone] não pode ser vazio!");
            flag = 3;
        }
        
        if (jTFEndereco.getText().equals("Endereço") || jTFEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [Endereço] não pode ser vazio!");
            flag = 4;
        }
        
        if (jTFNumero.getText().equals("Número") || jTFNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [Número] não pode ser vazio!");
            flag = 5;
        }
        
        if (jTFEmail.getText().equals("E-mail") || jTFEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [E-mail] não pode ser vazio!");
            flag = 6;
        }    
        
        if (flag == 0 && (pw.equals("jPasswordField1") || pw.equals("")) && (pw2.equals("jPasswordField2") || pw2.equals(""))) {
            JOptionPane.showMessageDialog(null, "A senha não pode ser nula!");
            flag = 10;
        }
        
        if (flag == 0 && pw.equals(pw2) && !pw.equals("")) {
            Usuarios u = new Usuarios(jTFNome.getText(), jTFEndereco.getText(), jTFNumero.getText(), jTFTelefone.getText(),
            jTFEmail.getText(), pw);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            new JFPrincipal().setVisible(true);
            this.setVisible(false);
            user.create(u);
            flag = 1;
            
        }
       
        if (flag==0) {
           System.out.printf("\n%d", flag);
           jPasswordField1.setText("");
           jPasswordField2.setText("");
           JOptionPane.showMessageDialog(null, "As senhas precisam ser iguais!");
        }
        
    // fecha DataSource
    dataSource.closeDataSource();
    
    }//GEN-LAST:event_CriarJanelaCadastroActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals("jPasswordField1"))
        {
            jPasswordField1.setText("");
            jPasswordField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals(""))
        {
            jPasswordField1.setText("jPasswordField1");
            jPasswordField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTFEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusGained
        // TODO add your handling code here:
        if(jTFEmail.getText().equals("E-mail"))
        {
            jTFEmail.setText("");
            jTFEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTFEmailFocusGained

    private void jTFEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusLost
        // TODO add your handling code here:
        if(jTFEmail.getText().equals(""))
        {
            jTFEmail.setText("E-mail");
            jTFEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTFEmailFocusLost

    private void jTFNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumeroFocusGained
        // TODO add your handling code here:
        if(jTFNumero.getText().equals("Número"))
        {
            jTFNumero.setText("");
            jTFNumero.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTFNumeroFocusGained

    private void jTFNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumeroFocusLost
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(jTFNumero.getText().equals(""))
        {
            jTFNumero.setText("Número");
            jTFNumero.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTFNumeroFocusLost

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTFEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEnderecoActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEnderecoActionPerformed

    private void jTFEnderecoAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTFEnderecoAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEnderecoAncestorRemoved

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(jPasswordField2.getText().equals("jPasswordField2"))
        {
            jPasswordField2.setText("");
            jPasswordField2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        if(jPasswordField2.getText().equals(""))
        {
            jPasswordField2.setText("jPasswordField2");
            jPasswordField2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jTFTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefoneActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefoneActionPerformed

    private void jTFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        CriarJanelaCadastroActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void CriarJanelaCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarJanelaCadastro1ActionPerformed
        new JFPrincipal().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
        
    }//GEN-LAST:event_CriarJanelaCadastro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarJanelaCadastro;
    private javax.swing.JButton CriarJanelaCadastro1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
}
